'use client';
import React, { useState } from 'react';
import { IoMdInformationCircleOutline } from 'react-icons/io';

const InfoIcon = () => {
  const [showTooltip, setShowTooltip] = useState(false);

  return (
    <div className="relative">
      <IoMdInformationCircleOutline
        size={24}
        color="#fff"
        className="cursor-pointer"
        onMouseEnter={() => setShowTooltip(true)}
        onMouseLeave={() => setShowTooltip(false)}
      />
      {showTooltip && (
        <div className="absolute right-0 mt-2 w-64 p-2 bg-gray-700 text-white text-sm rounded shadow-lg">
          This content is generated by AI using reliable and trusted
          sources. While every effort has been made to ensure
          accuracy, please note that it may not always reflect human
          expertise or judgment. Use discretion and consult additional
          sources if needed.
        </div>
      )}
    </div>
  );
};

export default InfoIcon;
